### ISSUE TITLE
[FR] Add character, words and page number

### ISSUE THREAD

**Issue by Mara-Li** [CattailNu/obsidian-file-info-panel-plugin#1]
Hello !
I think it's a good idea to do as the "get info" plugin of Chetachi, ie adding a :
- Word number 
- Page number (with options/personnalization)
- Characters number
The get info plugin of chetachi doesn't work on mobile, that's why I think it's a good idea to do that with your plugin !

**Comment by CattailNu** [comment]
What do you mean by page number?

**Comment by Mara-Li** [comment]
There is some formula to calculate the number of page, using char number and char per page : `word_in_file/word_parameters`
If I have "300 words per page" in my parameters, and a file with 750 words, I will have ~750/300= 2.5 pages

**Comment by CattailNu** [comment]
Please test the current "main".  I added what you requested and paragraph count and a word frequency analysis.
