### ISSUE TITLE
[Feature] Hotkey for "Show Info Pane"

### ISSUE THREAD

**Issue by huyz** [CattailNu/obsidian-file-info-panel-plugin#10]
Just as with:
- Backlinks: Show backlinks pane
- Tag pane: Show tag pane

can we have a "Show file info pane" hotkey?

The problem with the "Show/Hide File Info Panel" shortcut is that it hides first before it shows.  So sometimes I have to hit that shortcut once, sometimes I have to hit that shortcut twice, which isn't very consistent.  I just need a "Show" so I can be sure that the info shows up after one keystroke.

**Comment by CattailNu** [comment]
Fix coming in the next release (1.3). - you'll be able to assign your own hotkey to the new commands.
