### ISSUE TITLE
[Feature] For images, show some basic image metadata

### ISSUE THREAD

**Issue by huyz** [CattailNu/obsidian-file-info-panel-plugin#11]
It would be nice if, for images, the panel would display:
- Image size: 1600 × 1200 pixels
- Image DPI: 72 pixels/inch

This comes from https://forum.obsidian.md/t/image-size-in-images-pop-up-explorer/43909

**Comment by CattailNu** [comment]
Fix coming in the next release (1.3).  It doesn't show DPI (printer spec) or PPI, but does show pixel width/height.
