### ISSUE TITLE
Styling doesn't seem to match the screenshots in Obsidian v1

### ISSUE THREAD

**Issue by ianyoung** [CattailNu/obsidian-file-info-panel-plugin#12]
I'm using Obsidian v1.0.3 and the styling doesn't seem to match the screenshots.

<img width="289" alt="obsidian-info-panel" src="https://user-images.githubusercontent.com/66717/205747829-d08c4630-aec8-44ba-9cf2-b6c56c7ddcd6.png">

Have they changed or does it need updating for v1?

**Comment by Liong1976** [comment]
The same here

**Comment by CattailNu** [comment]
A fix for this is coming.  It appears that an update has broken the formatting of button css.  I've had this same issue in a few different non-obsidian projects.  I'm looking at the other issues too and I'll roll out an update.
