### ISSUE TITLE
Tested on android

### ISSUE THREAD

**Issue by paromey** [CattailNu/obsidian-file-info-panel-plugin#2]
Hi! So i tried testing this on android and the information doesn't show up on the plug in. Settings are good and all enabled but this is what happens when i try to open the file info pane.
![ezgif-2-f15261d0d2](https://user-images.githubusercontent.com/93504849/146632658-65822699-6587-4d8a-a656-826da57dda07.gif)

**Comment by CattailNu** [comment]
Also add option for vault relative path display.

**Comment by CattailNu** [comment]
Check and see if latest version (1.2.3) works.

**Comment by CattailNu** [comment]
I have someone who said it worked for them.  Closing the issue.
