### ISSUE TITLE
Some Visual Arrangements of the Side Panel

### ISSUE THREAD

**Issue by chrisgrieser** [CattailNu/obsidian-file-info-panel-plugin#3]
Hi! I was just styling your plugin's side panel for my theme, but I noticed a few things which I also could not change solely via CSS without breaking something else.

![image](https://user-images.githubusercontent.com/73286100/146635930-65adc208-c44a-4fd1-a474-0d5dce450937.png)

**Comment by CattailNu** [comment]
I have everything but the vault relative path working and will appear in the next release.  The path is linked to the android display issue so I'll fix it with that.

**Comment by CattailNu** [comment]
Thank you for the excellent feedback!
