### ISSUE TITLE
Add option to not show filtered words

### ISSUE THREAD

**Issue by chrisgrieser** [CattailNu/obsidian-file-info-panel-plugin#4]
The word frequency report is fantastic! Could you add an option to *not* show the filtered words? right now it's only possible to turn off the filtering entirely, or to turn on the filtering and showing the filtered words in a second textarea.

I assume many people like me really do not care about the filtered words, so an option to only show the first text area with the unfiltered words would be great. (could be the default option, too.)

**Comment by CattailNu** [comment]
Thank you for the feedback!  I have added a "show filtered words" option that will appear in the next release.
