### ISSUE TITLE
Info for selected text doesn't work on Live Preview. 

### ISSUE THREAD

**Issue by akadormouse** [CattailNu/obsidian-file-info-panel-plugin#6]

**Comment by CattailNu** [comment]
Yes, tried to fix this yesterday but couldn't find a working example/syntax to fix it.

**Comment by akadormouse** [comment]
Looks as if CM6 is more problematic for plugin developers than Licat expected

**Comment by CattailNu** [comment]
Latest version should have this fixed.  Not sure it's a CM6/general developer problem so much. This is my first typescript project, first obsidian plugin dev project, and so on.  Most likely, experienced devs (for this language) would be fine.
