### ISSUE TITLE
IOS - No Current File

### ISSUE THREAD

**Issue by bladecoates** [CattailNu/obsidian-file-info-panel-plugin#7]
When trying the plug-in with BRAT on my phone I'm getting "No Current File" in the file info panel. No other text/data is displayed. I'm interested in helping you getting this running on IOS as I do a lot of blog post drafts on both my iPhone and iPad. Video attached. This is with the current version of Obsidian in the App Store. I have not tried the insider version that was release a couple of days ago. 

IOS: 15.2.1
Device: IPhone 13 Pro Max
Obsidian App Version: 1.0.5

https://user-images.githubusercontent.com/4097682/149762386-b703767d-b0df-4b8d-be05-a881f5e53897.MOV

https://user-images.githubusercontent.com/4097682/149762402-1deb7eb7-1d71-4d2a-97ad-e27f7bff98c5.MOV

**Comment by CattailNu** [comment]
I tried something new today and it still does not work.  If you have any suggestions for how to fix the code, I'd appreciate it.

**Comment by CattailNu** [comment]
Check and see if latest version 1.2.3 works.

**Comment by bladecoates** [comment]
That appears to have done the trick. I'll play around with it the next couple of days and post back if I notice anything broken between desktop and iOS.


![image](https://user-images.githubusercontent.com/4097682/150613981-b171bbdc-639f-4fcb-b9ab-ec51bf67674e.png)
