### ISSUE TITLE
Check if `activeFile` exists before using

### ISSUE THREAD

**Issue by shabegom** [CattailNu/obsidian-file-info-panel-plugin#8]
https://github.com/CattailNu/obsidian-file-info-panel-plugin/blob/eead561d4eb09490fa6ffe24b437893d1f6d50a7/main.ts#L235

You have if statements that are checking `activeFile()`, but when a vault first loads there is no `activeFile` and so the plugin causes a lot of typeErrors logged to the dev console. Please check that there is an `activeFile` before using it.

**Comment by CattailNu** [comment]
Whoops!  Good catch!  Fixed in 1.2.5.
