### ISSUE TITLE
Exclude URLs

### ISSUE THREAD

**Issue by heliostatic** [CattailNu/obsidian-file-info-panel-plugin#9]
Hi! Love the plugin. I'm trying to exclude URLs from the word count. I've tried adding a standard regex to exclude in the filter list, but without success. Is there a current way to do this?

**Comment by CattailNu** [comment]
It's not finding it because the "words" are split before the pattern is applied, so www.Cattail.Nu goes in as www, Cattail, and Nu.  I'll give this some thought on how to provide the functionality.

**Comment by CattailNu** [comment]
Fix coming in the next release (1.3).
